### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined / originalHandleRequest = io.Manager.prototype.handleRequest;

### ISSUE THREAD

**Issue by sombriks** [nkashyap/ConsoleJS#10]
[sombriks@sephiroth ConsoleJS]$ nodemon
[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: _._
[nodemon] starting `node ./Server/Start.js`
Remote console URL: http://sephiroth:8082
/home/sombriks/git/ConsoleJS/Server/Server.js:34
    originalHandleRequest = io.Manager.prototype.handleRequest;
                                      ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.start (/home/sombriks/git/ConsoleJS/Server/Server.js:34:39)
    at Object.<anonymous> (/home/sombriks/git/ConsoleJS/Server/Start.js:4:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[nodemon] app crashed - waiting for file changes before starting...
^C[sombriks@sephiroth ConsoleJS]$

**Comment by sombriks** [comment]
i am not sure, but i think it's related to breaking changes on Socket.io

which version used to work with ConsoleJS?
